### ISSUE TITLE
Skirmish Ally Icons Graphic Name

### ISSUE THREAD

**Issue by Gavvers** [MHeasell/rwe#59]
https://github.com/MHeasell/rwe/blob/f2c16ea41a792b65f267d81337548ebaaf92c831/src/rwe/ui/UiFactory.cpp#L658

Using retail TA discs, it looks like the graphic name at that line should be "`ally icons`" rather than "`TEAMICONSx`". Does that change with the TA patches? I haven't applied them at this time.

**Comment by MHeasell** [comment]
It's been a while since I looked at this, but IIRC the team icons were
changed in one of the official patches. I imagine the behaviour of RWE as
it stands correctly matches the behaviour of TA with the 3.1 patch applied.
If that's the case then I don't want to change it unless there is some
stronger motivation for doing so.
