### ISSUE TITLE
"Number of labels does not match number of sprites"

### ISSUE THREAD

**Issue by tgunnoe** [MHeasell/rwe#61]
Manjaro Linux
at repo tip

Successful compilation but when clicking on "skirmish" in the menu I get this message, and the game exits.  Not sure what i'm missing

**Comment by MHeasell** [comment]
Can you provide information about the game data you are using? Ideally
where you got it + hashes. I will need to obtain a copy of the data myself
to attempt to reproduce this issue.

This error occurs when the engine attempts to create a "staged" UI button
-- that is, a button that lets you cycle through a set of choices -- but
the number of frames in the GAF animation the engine has loaded for the
button does not match the number of choices the button is meant to cycle
between.

This could either be due to an engine bug or because of bad game data.

**Comment by tgunnoe** [comment]
They come from the Total Annihilation Commander Pack on GOG.com.
I will obtain the ones from the original disc and report back.
totala1.hpi sha256sum
c3890a78e627e6e334f671f65ec418cd40d15ad2ad4110e931bb3dfced0814c3

totala2.hpi sha256sum
043e321169f73157812ec8e65b5fae29898ae3f41e527bc419801d18cf0cbe63

**Comment by MHeasell** [comment]
Those hashes are correct. I reproduced your problem by running RWE with just those files in the RWE data directory.

This isn't really supported -- the TA 3.1 patch data (rev31.gp3) is essentially required. The 3.1 patch both added new data and made changes to the TA exe in order to read it, and RWE attempts to match the version 3.1 behaviour.

Admittedly the failure mode of TA is a bit nicer -- if you run the TA 3.1 exe with just totala1.hpi and totala2.hpi, it doesn't crash, but instead displays grey in place of buttons whose sprites it couldn't load. This happens for the player team buttons in the skirmish menu. This is probably the button that RWE is crashing trying to load, as the name of the sprite used for this button changed some time between TA 1.0 and TA 3.1.

Add rev31.gp3 to your data directory and this error should go away. RWE also works fine if you copy/symlink the whole TA directory, or invoke it with the `--data-path=/path/to/your/data` option, pointing at your TA directory.

**Comment by tgunnoe** [comment]
Aaah thanks! That was indeed the problem. I followed the documentation to the word, so in the copy command i didnt copy the 3.1 patch

**Comment by MHeasell** [comment]
Oh right, yes I can see that's misleading. I'll update the readme instructions.
