### ISSUE TITLE
Failed to create logger

### ISSUE THREAD

**Issue by feugen** [MHeasell/rwe#69]
On following your readme on how to build and run the application on linux, I get a critical Error: "Failed to create logger".
All I can do is to close the window and the application exits.

**Comment by MHeasell** [comment]
The logger cannot be created because the local data path does not exist.

I have committed b6c175c4c736e00816bd05918255704208c52118 so now the program creates the local data path if it does not exist. This allows the logger to create the log file.

However you will likely still encounter an error if you do not place some game data inside the `Data` subdirectory in the local data directory, or pass `--data-path` on the command line to specify a path to read game data from.
